### ISSUE TITLE
Feature request: Let us go back to the level select, keeping current cheats

### ISSUE THREAD

**Issue by Redyn** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#200]
In the mobile version of Sonic 2, if you had debug mode enabled, you could go back to the level select screen by tapping Sonic's life icon. This was a nigh essential feature, as quitting a stage via the pause menu would disable debug mode, forcing you to enable it again.

Unless I missed something, this feature doesn't exist here, and there is no way of quitting a level without losing level select, debug mode, and any other enabled cheats.

So please give us a way of returning to the level select and keep current cheats for both Sonic 1 and 2. Having to do the level select and debug mode codes all over again all the time is a major pain in the ass.

**Comment by MGRich** [comment]
This sounds like a script thing that may not happen because of platform stuff? Heavily unsure though, assigning RDC and leaving this open.

**Comment by Rubberduckycooly** [comment]
RMG is correct, this is likely a script bug, though I can't say if it's an issue on our end or on Segas end, as Sega forever especially has been known to cause a lot of bugs even on the base version, I'll give a look into it to check if it's an issue on our end, and if so, to fix it. If the issue is not on our end (which is the case if you're not using scripts, but rather just your datafile) then it's likely a Sega forever bug, and the fix is to use a datafile from an older version of the game

**Comment by Redyn** [comment]
It's not a Sega Forever bug, as I'm using data files ripped from the last non-SF versions of Sonic 1 and 2.

I'm also using the decompiled scripts. Specifically, the last commit (bf89ff269dbb661dffc008bc4d24c89cb1a50c94).
