### ISSUE TITLE
Where are the save files stored?

### ISSUE THREAD

**Issue by mad-ady** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#201]
Hello!
I've compiled and set this up on my kid's linux computer. The binary (and resource files) went in /usr/share/games/sonic (which is read-only for the current user). They kids can save their progress, but it's lost when exiting the game.
Is the game trying to save in the same place where the binary is? Or in the current working directory? Sorry, I didn't have time to try it out.
The end goal is for two users to share the same binary/resource, but have their own save files (per user). One way to do it would be through some symlink trickery, but I'd thought I'd ask first for the correct way...
Thanks!

**Comment by MGRich** [comment]
They *should* be SData and UData in the executable directory, but I'm not sure how it's handled on Linux. I'll leave this open until RDC clarifies.

**Comment by Rubberduckycooly** [comment]
> They *should* be SData and UData in the executable directory, but I'm not sure how it's handled on Linux. I'll leave this open until RDC clarifies.

This is correct, they should be stored there. The only reason that they wouldn't be is because someone changed the base path (which I don't think anyone did) OR for  *some* reason the game doesn't have write permissions, and therefore is unable to write the files to the disk, though I can't say for sure that it's either because I don't own a Linux machine so I haven't tested on it

**Comment by mad-ady** [comment]
Are SData/UData directories or simple files? Are they created on startup, or after passing a stage? I'd like to test a bit. For now I've added world writable permissions on that folder, but haven't had time to play for long enough to pass on the next stage.
