### ISSUE TITLE
Start Button not working on Title Screen and Sonic 2 Special Stages

### ISSUE THREAD

**Issue by mn2301** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#354]
Tested on a Flatpak build on Fedora 36
The start button doesn't start the game at the PRESS BUTTON screen, and it doesn't pause at the Sonic 2 Special Stages.
Clicking the screen with the mouse does do the action (whole screen on the PRESS BUTTON screen and the invisible pause button on special stage)
The start button works as intended everywhere else.
Tested with 3.5.0 and 3.7.1 Data.rsdk for Sonic 1 and 1.3.5 and 1.5.2 for Sonic 2

Additionally, the 1.5.2 version of Sonic 2 doesn't seem to have the B button quirk on the Special Stage

**Comment by awe444** [comment]
This issue seems to overlap with https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/issues/344

I too can report that builds from recent commits result in an unresponsive title screen. I'm running on a minimal setup without a mouse or touchpad (keyboard and gamepad only), and in my case it appears impossible to advance past the title screen. Pressing Enter/Return on the keyboard doesn't work, nor do any other keys.

I've confirmed it works normally when built from [this commit](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/b59c2d65c62a4fc1798d5a7a51d73e867ae2cc17), so if I have time I can try to isolate which later commit broke it

**Comment by Espio419** [comment]
> 

Building from that commit fixed the issue for me. It' also compatible with the recent update to Sonic 1 Forever.

**Comment by MegAmi24** [comment]
Fixed in [93f8767](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/93f876731437a84f7038d62d273df734649da674)
