### ISSUE TITLE
S1 & S2: Can't get Elemental Shields (S3 items) into Time Attack

### ISSUE THREAD

**Issue by werster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#38]
In the core games, if you change the options to S3 items in game, and then Game Over, when you go to Time Attack, the Elemental Shields are accessible in Time Attack. If you select Sonic + Tails and do the same thing, you also get Sonic + Tails in Time Attack.

In this version, doing the same thing does not get you the Elemental Shields in Time Attack, but it does give you Sonic + Tails.

Ideally the game options would just extend to Time Attack mode so there would be no need to Game Over at all.

**Comment by Rubberduckycooly** [comment]
it should not give you sonic + tails (that's a bug we've fixed), and it was an intentional choice not to allow game options on time attack as that's how it was in the original, you can only play as sonic, with default options to keep it fair and balanced for everyone's times

we may consider changing this in future if there's enough support, but it wont be until after we've fixed most of the bugs we're working on
