### ISSUE TITLE
S1,2&CD: Pressing B while in-game makes Sonic jump and pauses the game

### ISSUE THREAD

**Issue by xKizame** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#8]
I don't know if this is only happens to me but, everytime i press B, the game makes the character jump while pausing the game.

This happens on the Sonic CD Decomp too, it's not really game breaking but it gets a bit annoying after a few minutes.

**Comment by TheGershon** [comment]
Same here, regardless of whether I'm using Keyboard or an xinput device. The B input pauses along with it's usual input, even if I remap it to somewhere else.

**Comment by ToruTheRedFox** [comment]
that's not a bug with the decomp, it's wonky button mapping in the versions of the mobile releases where they added controller support
the only way I know of fixing this is fixing the scripts to read the buttons correctly

**Comment by RosalinaFan573** [comment]
> the only way I know of fixing this is fixing the scripts to read the buttons correctly
You can also try using a different version of the APK, specifically ones with "xplode" and "api_key.txt" in the assets folder

**Comment by Rubberduckycooly** [comment]
this is "intentional", someone on the sega forever team added this for some reason, so its not technically a bug, you'll probably have to use a pre-sega forever data.rsdk if you dont want this "feature"

**Comment by JakeNagare** [comment]
I did some more research into this since it only seemed to be a problem with certain versions of the APK and well this is apparently ONLY in the latest versions of the "Sonic the Hedgehog Classic" and "Sonic the Hedgehog 2 Classic" APKs.  Sonic the Hedgehog Classic v3.5.0, and Sonic the Hedgehog 2 Classic v1.5.0 are fine and don't have this issue.

**Comment by ToruTheRedFox** [comment]
what person on the SEGA Forever team's idea was it to keep breaking these games with every update they make to them?

like, how do you mess up something as simple as smoothly scrolling back?

**Comment by Toonerz** [comment]
> 
> 
> I did some more research into this since it was only a problem with certain versions of the APK and well this is apparently ONLY in the latest versions of the "Sonic the Hedgehog Classic" and "Sonic the Hedgehog 2 Classic" APKs. Sonic the Hedgehog Classic v3.5.0, and Sonic the Hedgehog 2 Classic v1.5.0 are fine and don't have this issue. Do not get 3.5.1 or 1.5.1 respectively or you'll have this amazing "feature".

There is no Sonic 2 1.5.0, though? Unless this is referring to a pre SEGA Forever version?

**Comment by RosalinaFan573** [comment]
> > I did some more research into this since it was only a problem with certain versions of the APK and well this is apparently ONLY in the latest versions of the "Sonic the Hedgehog Classic" and "Sonic the Hedgehog 2 Classic" APKs. Sonic the Hedgehog Classic v3.5.0, and Sonic the Hedgehog 2 Classic v1.5.0 are fine and don't have this issue. Do not get 3.5.1 or 1.5.1 respectively or you'll have this amazing "feature".
> 
> There is no Sonic 2 1.5.0, though? Unless this is referring to a pre SEGA Forever version?

It looks like you need to use 1.3.5 for Sonic 2.

**Comment by JoeWeigmanVideo** [comment]
As I've stated in the Retro Engine Modding Discord server, This "Feature" from what I can tell was added after the sega forever team attempted to remove the level selects from being accessible for a brief time (This version was archived on Sonic Retro for those wondering). Highly doubt they tested this with a controller, it isn't noticeable throughout the game when using a touch screen until you go into the level select and enable debug mode which is also mapped to the B button.

My personal take is that someone was butthurt about people being able to access debug for some reason and first tried to remove the level selects, after being told they couldn't do that they added this b button pause to make using debug more annoying to use. here's some footage of me demonstrating this in the most recent mobile version for iOS:
https://cdn.discordapp.com/attachments/356533377559429151/801199987043598356/video0.mp4

**Comment by ViperAcidZX** [comment]
I noticed the mod Press Start Fix ([Sonic 1](https://gamebanana.com/mods/38), [Sonic 2](https://gamebanana.com/mods/34139)) by Glitchgod0 seemed to have fixed this annoying "feature" when using a Data.rsdk file (or its extracted data files) that's newer than 3.5.1 and 1.5.1 for Sonic 1 and Sonic 2 respectively (I tested with v3.7.0 for Sonic 1, Sonic 2 never got an update past v1.5.1 on Android since October 2021), but lacks a ``mod.ini`` file to work with the newer version of the decompilation and its mod loading features. A user on GameBanana for the Sonic 2 version of the Press Start Fix made this quick config file since Glitchgod0 appears to have abandoned this mod and it does work on the Sonic 1 version too.

**Comment by MegAmi24** [comment]
The decompiled scripts don't replicate the b-pause bug, so by extension using any script mod will fix this
